language: node_js
node_js: '8.12.0'
env:
  global:
  - secure: XjBf3YUyPyBfes2XqIABmHdiwIA+d5qz2YRpTm8tdxfUJlf88Kpo7bOGInaSG2X1NJ1Lt3iTAIlgB5E2bLn45BDI0qlO05WITHn1sZ+ETm54EmDxk655dnmz6pYK73yHLUnUYFT7tM6uDbRyz7hKunruY4unAeLCB1aL7ymo+SE=
  - secure: vWm69FUJN+nhW/RI0d6lF/O1AOFcL2IDN0W68KUKiYmmQfuLLDA9p8vRP+Im065d7GszjuljRWn3qJvCT8a7HdYHuJwQD3j4o+heXtXqIJU167rgN3x4h6l8a3aZtgoff0Pr8zCyuknbOntK/1pxlDUa7Js/BUHFojE/PWnf1WQ=
  - secure: m/lR7bf1FVlmiqR8h4OCIicTiiAjO95k7MPE+Yx2kLT1FVoW3kfJ3ckxXygKaydKPHbjstVwXzenbU8cD/2ir94YlkUJID65AkFxLvYI2WZTRLXXyj3dbwEIaI1rn21WdfgeAdyZfglNTSk5sCUojBCIubHYKzTeWbdGnNSGHrg=
  - secure: u8dTQviwfBiBtkwADV+y4VIvoKD4XBf2gt04fR4yBlBWJjHk+Y5hA8SP7FVpcwfy7qGMmeVvEl0Hx/MyI4DRM8xjUKxw1v3eagyZUav4Go4ebCvTFqGM8PjlYPOLsKAPysYTMqJlnHD4NHCQagRqRzYg2oAR6YVOjpYY5oUiWRw=
before_install: npm install -g grunt-cli
install: npm install
before_script: grunt build
after_success:
- chmod +x ./travis-install-git-ftp.sh
- chmod +x ./travis-deploy.sh
- ./travis-install-git-ftp.sh
- ./travis-deploy.sh
